/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main (String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println("Starting QCalc..");

        StandardCalculator calc = new StandardCalculator();

        try {
            calc.add(Double.MAX_VALUE - 1.0, 1.0); // This should not cause an overflow
            calc.printResult();

            calc.add(Double.MAX_VALUE / 2.0, Double.MAX_VALUE / 2.0); // This should not cause an overflow
            calc.printResult();
        } catch (ArithmeticException e) {
            System.err.println(e.getMessage());
        }

        



    }

}
